# Generated by Django 5.2.5 on 2025-09-17 00:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('head_of_department', models.CharField(max_length=250)),
                ('number_of_student', models.PositiveIntegerField(default=0)),
                ('department_start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('grade_level', models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN', 'Kindergarten'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FileField(upload_to='assignments/')),
                ('assignment_class', models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN', 'Kindergarten'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], max_length=50)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.BooleanField(default=False)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letter_grade', models.CharField(choices=[('A+', 'A+ (90-100%)'), ('A', 'A (80-89%)'), ('A-', 'A- (75-79%)'), ('B+', 'B+ (70-74%)'), ('B', 'B (65-69%)'), ('B-', 'B- (60-64%)'), ('C+', 'C+ (55-59%)'), ('C', 'C (50-54%)'), ('C-', 'C- (45-49%)'), ('D+', 'D+ (40-44%)'), ('D', 'D (35-39%)'), ('F', 'F (0-34%)')], max_length=2)),
                ('numerical_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.TextField(blank=True, max_length=1000)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.enrollment')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='teacher.assignment')),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('mobile', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('joining_date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='teachers/')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
    ]
