# Generated by Django 5.2.5 on 2025-09-11 02:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_options_student_user_and_more'),
        ('teacher', '0003_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letter_grade', models.CharField(choices=[('A+', 'A+ (90-100%)'), ('A', 'A (80-89%)'), ('A-', 'A- (75-79%)'), ('B+', 'B+ (70-74%)'), ('B', 'B (65-69%)'), ('B-', 'B- (60-64%)'), ('C+', 'C+ (55-59%)'), ('C', 'C (50-54%)'), ('C-', 'C- (45-49%)'), ('D+', 'D+ (40-44%)'), ('D', 'D (35-39%)'), ('F', 'F (0-34%)')], max_length=2)),
                ('numerical_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.TextField(blank=True, max_length=1000)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='teacher.assignment')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to='teacher.teacher')),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'ordering': ['-graded_at'],
            },
        ),
    ]
