# Generated by Django 5.2.5 on 2025-09-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_assignment_max_score_assignment_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_class',
            field=models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN', 'Kindergarten'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
