# Generated by Django 5.2.5 on 2025-09-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_assignment_assignment_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
    ]
