# Generated by Django 5.2.5 on 2025-09-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exams_type', models.CharField(choices=[('class_test', 'Class_Test'), ('exams', 'Exams'), ('hostel', 'Hostel'), ('transport', 'Transport')], max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
