# Generated by Django 5.2.5 on 2025-09-17 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone', models.CharField(max_length=15)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone', models.CharField(max_length=15)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_email', models.EmailField(max_length=254)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_class', models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN', 'Kindergarten'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('section', models.CharField(max_length=50)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('fees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_with_fees', to='finance.fees')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.parent')),
                ('user', models.OneToOneField(help_text='The user account associated with this student.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
