# Generated by Django 5.2.5 on 2025-08-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='preseent_address',
            new_name='present_address',
        ),
    ]
