# Generated by Django 5.2.5 on 2025-09-09 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('student', '0002_rename_preseent_address_parent_present_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_with_fees', to='finance.fees'),
        ),
    ]
