# Generated by Django 5.2.5 on 2025-08-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='j16HW8KtH0Kk64kV284fv5B9Jr28aVvN', editable=False, max_length=100, unique=True),
        ),
    ]
